# Generated by Django 3.2.13 on 2022-05-20 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coral',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coral',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
