# Generated by Django 3.2.13 on 2022-05-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coral', '0002_auto_20220520_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coral',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coral',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='coral',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('deceased', 'Deceased')], max_length=20),
        ),
    ]
